version: 2

multi-ecosystem-groups:
  monthly-dependencies:
    schedule:
      interval: monthly

updates:
  - package-ecosystem: uv
    directory: /
    target-branch: dev
    multi-ecosystem-group: monthly-dependencies

  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    multi-ecosystem-group: monthly-dependencies
