"""Regression tests for PiecewiseCF (C3).

These tests pin the *PiecewiseCF* LOD values against themselves — not against
PiecewiseWLS.  WLS is a local optimizer that can converge to a suboptimal
partition; CF's exhaustive discrete search is provably more correct when the
two methods disagree (confirmed by the C2.2 partition audit: CF wins RSS in
11/13 different-partition cases).

Pinned LOD reference values were recorded on 2026-03-28 from a baseline
scratch run on the 27-peptide EncyclopeDIA reference dataset
(data/demo/one_protein.csv).  The same-partition subset (14 peptides) is also
asserted to agree with PiecewiseWLS within 1e-4 to guard against any
regression in the constraint enforcement or segment-fit code.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from loqculate import PiecewiseCF
from loqculate.io import read_calibration_data
from loqculate.models import MODEL_REGISTRY, PiecewiseWLS
from loqculate.utils.weights import inverse_sqrt_weights

# ---------------------------------------------------------------------------
# Demo data
# ---------------------------------------------------------------------------

_DEMO_DIR = Path(__file__).parent.parent / "data" / "demo"
_DATA_FILE = _DEMO_DIR / "one_protein.csv"
_CONC_MAP = _DEMO_DIR / "filename2samplegroup_map.csv"


@pytest.fixture(scope="module")
def reference_data():
    if not _DATA_FILE.exists():
        pytest.skip("Demo data not found")
    return read_calibration_data(str(_DATA_FILE), str(_CONC_MAP))


@pytest.fixture(scope="module")
def all_cf_fits(reference_data):
    """Fit PiecewiseCF on every peptide; return dict peptide -> fitted model."""
    fits = {}
    for pep in np.unique(reference_data.peptide):
        mask = reference_data.peptide == pep
        x = reference_data.concentration[mask]
        y = reference_data.area[mask]
        fits[pep] = PiecewiseCF(n_boot_reps=200, seed=42).fit(x, y)
    return fits


# ---------------------------------------------------------------------------
# Pinned LOD reference values (recorded 2026-03-28 — do not edit manually)
# ---------------------------------------------------------------------------

# Generated by: fit find_knot on all 27 reference peptides; record lod().
# Tolerance for regression check: 1e-8 (solver is deterministic).
_PINNED_LOD = {
    "ADTGIAVEGATDAAR": 0.0062758231,
    "DDTAQTVSEAR": 0.0285251525,
    "GEGFMVVTATGDNTFVGR": 0.2636370053,
    "GEGHWEILGVMPC[+57.0214635]MDPPR": 0.1580453571,
    "GYLVAMTGDGVNDAPSLK": 0.0193246396,
    "GYLVAMTGDGVNDAPSLKK": 0.0876019423,
    "HYGDQTFSSSTVK": 0.0095857559,
    "IVTEDC[+57.0214635]FLQIDQSAITGESLAVDK": 0.0767206646,
    "KADTGIAVEGATDAAR": 0.0083805522,
    "KQAIVQK": 0.1730602633,
    "KVTAVVESPEGER": 0.0089324663,
    "LMNGKPMK": 0.0700248860,
    "LSAIESLAGVEILC[+57.0214635]SDK": 0.0245494621,
    "LSLHEPYTVEGVSPDDLMLTAC[+57.0214635]LAASR": 0.0422363987,
    "MLTGDAVGIAK": 0.0189522594,
    "MYSYVVYR": 0.2734170172,
    "QLGLGTNIYNAER": 0.0476389947,
    "RGEGFMVVTATGDNTFVGR": np.inf,
    "SAADIVFLAPGLSAIIDALK": 0.0351098780,
    "SVEDFMAAMQR": 0.0226205879,
    "TLANTAVVIR": 0.0034752851,
    "TVEEDHPIPEDVHENYENK": 0.0078661607,
    "VLEFHPFDPVSK": 0.0085391033,
    "VTAVVESPEGER": 0.0300171326,
    "VVEILQNR": 0.002818856941376874,
    "YGLNQMADEK": 0.0260871510,
    "YGLNQMADEKESLVVK": 0.5546338758,
}

# Peptides with infinite LOQ under PiecewiseCF (n_boot_reps=200, seed=42).
_INFINITE_LOQ_PEPTIDES = frozenset(
    [
        "RGEGFMVVTATGDNTFVGR",
        "SAADIVFLAPGLSAIIDALK",
        "YGLNQMADEKESLVVK",
    ]
)

# Same-partition peptides: xjoin_cf and xjoin_wls agree to < 1e-6 (unsorted input).
# 13 peptides confirmed by the C2.2/C3 baseline run.
# MYSYVVYR excluded: xjoin diff = 5.4e-5 (refinement converges near WLS join
# but not within the 1e-6 hard threshold; LOD rel diff = 1.56e-4 — too large
# to assert 1e-4 agreement between two different fitting algorithms).
_SAME_PARTITION_PEPTIDES = frozenset(
    [
        "ADTGIAVEGATDAAR",
        "DDTAQTVSEAR",
        "GYLVAMTGDGVNDAPSLK",
        "HYGDQTFSSSTVK",
        "KQAIVQK",
        "KVTAVVESPEGER",
        "LSAIESLAGVEILC[+57.0214635]SDK",
        "MLTGDAVGIAK",
        "QLGLGTNIYNAER",
        "TVEEDHPIPEDVHENYENK",
        "VTAVVESPEGER",
        "VVEILQNR",
        "YGLNQMADEK",
    ]
)


# ---------------------------------------------------------------------------
# Test 1: LOD matches pinned reference values
# ---------------------------------------------------------------------------


class TestLODRegression:
    def test_lod_matches_pinned_values(self, all_cf_fits):
        """PiecewiseCF.lod() must match the pinned reference within 1e-8.

        The solver is deterministic; any deviation signals a regression in
        find_knot, _fit_and_constrain, or the LOD formula itself.
        """
        failures = []
        for pep, ref_lod in _PINNED_LOD.items():
            cf = all_cf_fits[pep]
            got = cf.lod()
            if np.isfinite(ref_lod):
                rel = abs(got - ref_lod) / max(abs(ref_lod), 1e-12)
                if rel >= 1e-8:
                    failures.append((pep, ref_lod, got, rel))
            else:
                # Both should be infinite
                if np.isfinite(got):
                    failures.append((pep, "inf", got, np.nan))
        assert not failures, (
            f"LOD regression failures in {len(failures)} peptide(s):\n"
            + "\n".join(f"  {p}: expected {e}, got {g} (rel={r:.2e})" for p, e, g, r in failures)
        )

    def test_same_partition_lod_agrees_with_wls(self, reference_data, all_cf_fits):
        """Same-partition peptides: PiecewiseCF and PiecewiseWLS LODs must agree
        within 1e-4.  Both methods fit the same data with the same constrained
        parameters when they select the same partition.
        """
        failures = []
        for pep in _SAME_PARTITION_PEPTIDES:
            mask = reference_data.peptide == pep
            x = reference_data.concentration[mask]
            y = reference_data.area[mask]
            wls = PiecewiseWLS(init_method="legacy", n_boot_reps=0, seed=42).fit(x, y)
            lod_wls = wls.lod()
            lod_cf = all_cf_fits[pep].lod()
            if np.isfinite(lod_wls) and np.isfinite(lod_cf):
                rel = abs(lod_cf - lod_wls) / max(abs(lod_wls), 1e-12)
                if rel >= 1e-4:
                    failures.append((pep, lod_wls, lod_cf, rel))
        assert not failures, (
            f"Same-partition LOD agreement failed for {len(failures)} peptide(s):\n"
            + "\n".join(f"  {p}: WLS={w:.6f}, CF={c:.6f} (rel={r:.2e})" for p, w, c, r in failures)
        )


# ---------------------------------------------------------------------------
# Test 2: LOQ reproducibility
# ---------------------------------------------------------------------------


class TestLOQRegression:
    def test_loq_is_deterministic(self, reference_data):
        """Calling fit(x, y).loq() twice returns the identical value.
        PiecewiseCF is deterministic: same seed → same bootstrap → same LOQ.
        """
        pep = "ADTGIAVEGATDAAR"
        mask = reference_data.peptide == pep
        x = reference_data.concentration[mask]
        y = reference_data.area[mask]

        loq1 = PiecewiseCF(n_boot_reps=200, seed=42).fit(x, y).loq()
        loq2 = PiecewiseCF(n_boot_reps=200, seed=42).fit(x, y).loq()
        assert loq1 == loq2, f"LOQ not deterministic: {loq1} != {loq2}"

    def test_infinite_loq_peptides_remain_infinite(self, all_cf_fits):
        """Peptides identified as infinite-LOQ in the baseline run must stay
        infinite — a finite value here would indicate a silent regression in
        the bootstrap or the LOQ threshold search.
        """
        for pep in _INFINITE_LOQ_PEPTIDES:
            loq = all_cf_fits[pep].loq()
            assert not np.isfinite(loq), f"{pep}: expected infinite LOQ, got {loq:.6f}"


# ---------------------------------------------------------------------------
# Test 3: zero convergence failures
# ---------------------------------------------------------------------------


class TestConvergence:
    def test_no_nan_params(self, all_cf_fits):
        """PiecewiseCF must never produce NaN in any fitted parameter."""
        failures = []
        for pep, cf in all_cf_fits.items():
            for k, v in cf.params_.items():
                if np.isnan(v):
                    failures.append((pep, k, v))
        assert not failures, f"NaN params in {len(failures)} case(s): {failures}"

    def test_no_exceptions_on_all_peptides(self, reference_data):
        """fit() must not raise for any of the 27 reference peptides."""
        for pep in np.unique(reference_data.peptide):
            mask = reference_data.peptide == pep
            x = reference_data.concentration[mask]
            y = reference_data.area[mask]
            PiecewiseCF(n_boot_reps=0, seed=42).fit(x, y)


# ---------------------------------------------------------------------------
# Test 4: gram_inv is stored and correct
# ---------------------------------------------------------------------------


class TestGramInverse:
    def test_gram_inv_stored_after_fit(self, all_cf_fits):
        """_gram_inv must be set (not None) after fitting a non-degenerate peptide."""
        cf = all_cf_fits["ADTGIAVEGATDAAR"]
        assert cf._gram_inv is not None
        assert cf._gram_inv.shape == (2, 2)

    def test_gram_inv_matches_direct_computation(self, reference_data):
        """_gram_inv must equal the 2x2 inverse computed directly from the
        linear segment observations, within 1e-10.
        """
        pep = "VTAVVESPEGER"
        mask = reference_data.peptide == pep
        x = reference_data.concentration[mask]
        y = reference_data.area[mask]
        w = inverse_sqrt_weights(x)
        W = w**2

        cf = PiecewiseCF(n_boot_reps=0, seed=42).fit(x, y)
        knot_x = cf.params_["knot_x"]

        # Recompute G directly from the linear segment
        lin_mask = x > knot_x
        xL = x[lin_mask]
        WL = W[lin_mask]
        G = np.array(
            [
                [np.sum(WL * xL**2), np.sum(WL * xL)],
                [np.sum(WL * xL), np.sum(WL)],
            ]
        )
        expected_inv = np.linalg.inv(G)

        np.testing.assert_allclose(
            cf._gram_inv,
            expected_inv,
            rtol=1e-10,
            err_msg=f"_gram_inv does not match direct computation for {pep}",
        )


# ---------------------------------------------------------------------------
# Test 5: summary() returns finite values for fitted peptides
# ---------------------------------------------------------------------------


class TestSummary:
    def test_summary_finite_for_finite_lod_peptides(self, all_cf_fits):
        """summary() must contain finite values for slope, intercept_linear,
        intercept_noise, knot_x, and n_points for all peptides.
        LOD and LOQ may be inf for degenerate peptides.
        """
        required_finite_keys = [
            "slope",
            "intercept_linear",
            "intercept_noise",
            "knot_x",
            "n_points",
        ]
        failures = []
        for pep, cf in all_cf_fits.items():
            s = cf.summary()
            for k in required_finite_keys:
                if not np.isfinite(s[k]):
                    failures.append((pep, k, s[k]))
        assert not failures, f"Non-finite summary keys: {failures}"

    def test_summary_keys_complete(self, all_cf_fits):
        cf = next(iter(all_cf_fits.values()))
        keys = set(cf.summary().keys())
        assert {
            "slope",
            "intercept_linear",
            "intercept_noise",
            "knot_x",
            "lod",
            "loq",
            "n_points",
        } <= keys

    def test_predict_shape(self, reference_data):
        """predict() must return an array of the same length as the input."""
        pep = "KQAIVQK"
        mask = reference_data.peptide == pep
        x = reference_data.concentration[mask]
        y = reference_data.area[mask]
        cf = PiecewiseCF(n_boot_reps=0, seed=42).fit(x, y)
        x_new = np.linspace(0.001, 1.0, 20)
        preds = cf.predict(x_new)
        assert preds.shape == (20,)
        assert np.all(preds >= cf.params_["intercept_noise"] - 1e-10)


# ---------------------------------------------------------------------------
# Test 6: model registry
# ---------------------------------------------------------------------------


class TestRegistry:
    def test_piecewise_cf_in_registry(self):
        assert "piecewise_cf" in MODEL_REGISTRY
        assert MODEL_REGISTRY["piecewise_cf"] is PiecewiseCF
