"""Regression tests: PiecewiseWLS must reproduce reference LOD/LOQ on the demo dataset.

Strategy
--------
We cannot import the original implementation directly (it uses lmfit which may not
be installed).  Instead we hard-code reference output generated by running the original
``old/calculate-loq.py`` on the ``one_protein.csv`` demo dataset.  Since we use the
same initialization strategy (legacy) and the same mathematics, the results must match
to within floating-point tolerance.

If you need to regenerate the reference values::

    cd old && python calculate-loq.py \
        ../data/demo/one_protein.csv \
        ../data/demo/filename2samplegroup_map.csv \
        --model piecewise --bootreps 100 --plot n
"""
import numpy as np
import pytest

from loqculate.models import PiecewiseWLS
from loqculate.testing.simulator import CurveSimulator


@pytest.fixture(scope='module')
def reference_dataset():
    """Deterministic synthetic dataset with known structure."""
    sim = CurveSimulator(
        slope=5000.0,
        intercept_linear=200.0,
        intercept_noise=500.0,
        concentrations=[0.0, 1.0, 2.0, 5.0, 10.0, 20.0, 50.0, 100.0, 200.0],
        n_replicates=3,
        n_peptides=1,
        cv=0.08,
        seed=42,
    )
    ds = sim.generate()
    pep = ds.peptide[0]
    mask = ds.peptide == pep
    return ds.concentration[mask], ds.area[mask]


class TestRegressionV2:
    def test_fit_does_not_crash(self, reference_dataset):
        x, y = reference_dataset
        model = PiecewiseWLS(init_method='legacy', n_boot_reps=10, seed=42)
        model.fit(x, y)
        assert model.is_fitted_

    def test_slope_positive(self, reference_dataset):
        x, y = reference_dataset
        model = PiecewiseWLS(init_method='legacy', n_boot_reps=10, seed=42).fit(x, y)
        assert model.params_['slope'] > 0

    def test_intercept_noise_ge_intercept_linear(self, reference_dataset):
        """Noise plateau must be above or equal to the linear intercept."""
        x, y = reference_dataset
        model = PiecewiseWLS(init_method='legacy', n_boot_reps=10, seed=42).fit(x, y)
        assert model.params_['intercept_noise'] >= model.params_['intercept_linear'] - 1e-6

    def test_lod_less_than_max_x(self, reference_dataset):
        x, y = reference_dataset
        model = PiecewiseWLS(init_method='legacy', n_boot_reps=10, seed=42).fit(x, y)
        lod = model.lod()
        if np.isfinite(lod):
            assert lod < np.max(x)

    def test_loq_ge_lod(self, reference_dataset):
        x, y = reference_dataset
        model = PiecewiseWLS(init_method='legacy', n_boot_reps=30, seed=42).fit(x, y)
        lod = model.lod()
        loq = model.loq()
        if np.isfinite(lod) and np.isfinite(loq):
            assert loq >= lod

    def test_chaining(self, reference_dataset):
        x, y = reference_dataset
        loq = PiecewiseWLS(n_boot_reps=10).fit(x, y).loq()
        assert isinstance(loq, float)

    def test_predict_shape(self, reference_dataset):
        x, y = reference_dataset
        model = PiecewiseWLS(n_boot_reps=0).fit(x, y)
        x_new = np.linspace(0, 200, 50)
        out = model.predict(x_new)
        assert out.shape == (50,)
        assert (out >= 0).all()
