"""Regression tests for PiecewiseCF (C3).

These tests pin the *PiecewiseCF* LOD values against themselves — not against
PiecewiseWLS.  WLS is a local optimizer that can converge to a suboptimal
partition; CF's exhaustive discrete search is provably more correct when the
two methods disagree (confirmed by the C2.2 partition audit: CF wins RSS in
11/13 different-partition cases).

Pinned LOD reference values were recorded on 2026-03-28 from a baseline
scratch run on the 27-peptide EncyclopeDIA reference dataset
(data/demo/one_protein.csv).  The same-partition subset (14 peptides) is also
asserted to agree with PiecewiseWLS within 1e-4 to guard against any
regression in the constraint enforcement or segment-fit code.
"""

from __future__ import annotations

import warnings
from pathlib import Path

import numpy as np
import pytest

from loqculate import PiecewiseCF
from loqculate.io import read_calibration_data
from loqculate.models import MODEL_REGISTRY, PiecewiseWLS
from loqculate.models.piecewise_cf import _bootstrap_loop_cf, _bootstrap_vectorized_cf
from loqculate.utils.weights import inverse_sqrt_weights

# ---------------------------------------------------------------------------
# Demo data
# ---------------------------------------------------------------------------

_DEMO_DIR = Path(__file__).parent.parent / "data" / "demo"
_DATA_FILE = _DEMO_DIR / "one_protein.csv"
_CONC_MAP = _DEMO_DIR / "filename2samplegroup_map.csv"


@pytest.fixture(scope="module")
def reference_data():
    if not _DATA_FILE.exists():
        pytest.skip("Demo data not found")
    return read_calibration_data(str(_DATA_FILE), str(_CONC_MAP))


@pytest.fixture(scope="module")
def all_cf_fits(reference_data):
    """Fit PiecewiseCF on every peptide; return dict peptide -> fitted model."""
    fits = {}
    for pep in np.unique(reference_data.peptide):
        mask = reference_data.peptide == pep
        x = reference_data.concentration[mask]
        y = reference_data.area[mask]
        fits[pep] = PiecewiseCF(n_boot_reps=200, seed=42).fit(x, y)
    return fits


# ---------------------------------------------------------------------------
# Pinned LOD reference values (recorded 2026-03-28 — do not edit manually)
# ---------------------------------------------------------------------------

# Generated by: fit find_knot on all 27 reference peptides; record lod().
# Tolerance for regression check: 1e-8 (solver is deterministic).
_PINNED_LOD = {
    "ADTGIAVEGATDAAR": 0.0062758231,
    "DDTAQTVSEAR": 0.0285251525,
    "GEGFMVVTATGDNTFVGR": 0.2636370053,
    "GEGHWEILGVMPC[+57.0214635]MDPPR": 0.1580453571,
    "GYLVAMTGDGVNDAPSLK": 0.0193246396,
    "GYLVAMTGDGVNDAPSLKK": 0.0876019423,
    "HYGDQTFSSSTVK": 0.0095857559,
    "IVTEDC[+57.0214635]FLQIDQSAITGESLAVDK": 0.0767206646,
    "KADTGIAVEGATDAAR": 0.0083805522,
    "KQAIVQK": 0.1730602633,
    "KVTAVVESPEGER": 0.0089324663,
    "LMNGKPMK": 0.0700248860,
    "LSAIESLAGVEILC[+57.0214635]SDK": 0.0245494621,
    "LSLHEPYTVEGVSPDDLMLTAC[+57.0214635]LAASR": 0.0422363987,
    "MLTGDAVGIAK": 0.0189522594,
    "MYSYVVYR": 0.2734170172,
    "QLGLGTNIYNAER": 0.0476389947,
    "RGEGFMVVTATGDNTFVGR": np.inf,
    "SAADIVFLAPGLSAIIDALK": 0.0351098780,
    "SVEDFMAAMQR": 0.0226205879,
    "TLANTAVVIR": 0.0034752851,
    "TVEEDHPIPEDVHENYENK": 0.0078661607,
    "VLEFHPFDPVSK": 0.0085391033,
    "VTAVVESPEGER": 0.0300171326,
    "VVEILQNR": 0.002818856941376874,
    "YGLNQMADEK": 0.0260871510,
    "YGLNQMADEKESLVVK": 0.5546338758,
}

# Peptides with infinite LOQ under PiecewiseCF (n_boot_reps=200, seed=42).
_INFINITE_LOQ_PEPTIDES = frozenset(
    [
        "RGEGFMVVTATGDNTFVGR",
        "SAADIVFLAPGLSAIIDALK",
        "YGLNQMADEKESLVVK",
    ]
)

# Same-partition peptides: xjoin_cf and xjoin_wls agree to < 1e-6 (unsorted input).
# 13 peptides confirmed by the C2.2/C3 baseline run.
# MYSYVVYR excluded: xjoin diff = 5.4e-5 (refinement converges near WLS join
# but not within the 1e-6 hard threshold; LOD rel diff = 1.56e-4 — too large
# to assert 1e-4 agreement between two different fitting algorithms).
_SAME_PARTITION_PEPTIDES = frozenset(
    [
        "ADTGIAVEGATDAAR",
        "DDTAQTVSEAR",
        "GYLVAMTGDGVNDAPSLK",
        "HYGDQTFSSSTVK",
        "KQAIVQK",
        "KVTAVVESPEGER",
        "LSAIESLAGVEILC[+57.0214635]SDK",
        "MLTGDAVGIAK",
        "QLGLGTNIYNAER",
        "TVEEDHPIPEDVHENYENK",
        "VTAVVESPEGER",
        "VVEILQNR",
        "YGLNQMADEK",
    ]
)


# ---------------------------------------------------------------------------
# Test 1: LOD matches pinned reference values
# ---------------------------------------------------------------------------


class TestLODRegression:
    def test_lod_matches_pinned_values(self, all_cf_fits):
        """PiecewiseCF.lod() must match the pinned reference within 1e-8.

        The solver is deterministic; any deviation signals a regression in
        find_knot, _fit_and_constrain, or the LOD formula itself.
        """
        failures = []
        for pep, ref_lod in _PINNED_LOD.items():
            cf = all_cf_fits[pep]
            got = cf.lod()
            if np.isfinite(ref_lod):
                rel = abs(got - ref_lod) / max(abs(ref_lod), 1e-12)
                if rel >= 1e-8:
                    failures.append((pep, ref_lod, got, rel))
            else:
                # Both should be infinite
                if np.isfinite(got):
                    failures.append((pep, "inf", got, np.nan))
        assert not failures, (
            f"LOD regression failures in {len(failures)} peptide(s):\n"
            + "\n".join(f"  {p}: expected {e}, got {g} (rel={r:.2e})" for p, e, g, r in failures)
        )

    def test_same_partition_lod_agrees_with_wls(self, reference_data, all_cf_fits):
        """Same-partition peptides: PiecewiseCF and PiecewiseWLS LODs must agree
        within 1e-4.  Both methods fit the same data with the same constrained
        parameters when they select the same partition.
        """
        failures = []
        for pep in _SAME_PARTITION_PEPTIDES:
            mask = reference_data.peptide == pep
            x = reference_data.concentration[mask]
            y = reference_data.area[mask]
            wls = PiecewiseWLS(init_method="legacy", n_boot_reps=0, seed=42).fit(x, y)
            lod_wls = wls.lod()
            lod_cf = all_cf_fits[pep].lod()
            if np.isfinite(lod_wls) and np.isfinite(lod_cf):
                rel = abs(lod_cf - lod_wls) / max(abs(lod_wls), 1e-12)
                if rel >= 1e-4:
                    failures.append((pep, lod_wls, lod_cf, rel))
        assert not failures, (
            f"Same-partition LOD agreement failed for {len(failures)} peptide(s):\n"
            + "\n".join(f"  {p}: WLS={w:.6f}, CF={c:.6f} (rel={r:.2e})" for p, w, c, r in failures)
        )


# ---------------------------------------------------------------------------
# Test 2: LOQ reproducibility
# ---------------------------------------------------------------------------


class TestLOQRegression:
    def test_loq_is_deterministic(self, reference_data):
        """Calling fit(x, y).loq() twice returns the identical value.
        PiecewiseCF is deterministic: same seed → same bootstrap → same LOQ.
        """
        pep = "ADTGIAVEGATDAAR"
        mask = reference_data.peptide == pep
        x = reference_data.concentration[mask]
        y = reference_data.area[mask]

        loq1 = PiecewiseCF(n_boot_reps=200, seed=42).fit(x, y).loq()
        loq2 = PiecewiseCF(n_boot_reps=200, seed=42).fit(x, y).loq()
        assert loq1 == loq2, f"LOQ not deterministic: {loq1} != {loq2}"

    def test_infinite_loq_peptides_remain_infinite(self, all_cf_fits):
        """Peptides identified as infinite-LOQ in the baseline run must stay
        infinite — a finite value here would indicate a silent regression in
        the bootstrap or the LOQ threshold search.
        """
        for pep in _INFINITE_LOQ_PEPTIDES:
            loq = all_cf_fits[pep].loq()
            assert not np.isfinite(loq), f"{pep}: expected infinite LOQ, got {loq:.6f}"


# ---------------------------------------------------------------------------
# Test 3: zero convergence failures
# ---------------------------------------------------------------------------


class TestConvergence:
    def test_no_nan_params(self, all_cf_fits):
        """PiecewiseCF must never produce NaN in any fitted parameter."""
        failures = []
        for pep, cf in all_cf_fits.items():
            for k, v in cf.params_.items():
                if np.isnan(v):
                    failures.append((pep, k, v))
        assert not failures, f"NaN params in {len(failures)} case(s): {failures}"

    def test_no_exceptions_on_all_peptides(self, reference_data):
        """fit() must not raise for any of the 27 reference peptides."""
        for pep in np.unique(reference_data.peptide):
            mask = reference_data.peptide == pep
            x = reference_data.concentration[mask]
            y = reference_data.area[mask]
            PiecewiseCF(n_boot_reps=0, seed=42).fit(x, y)


# ---------------------------------------------------------------------------
# Test 4: gram_inv is stored and correct
# ---------------------------------------------------------------------------


class TestGramInverse:
    def test_gram_inv_stored_after_fit(self, all_cf_fits):
        """_gram_inv must be set (not None) after fitting a non-degenerate peptide."""
        cf = all_cf_fits["ADTGIAVEGATDAAR"]
        assert cf._gram_inv is not None
        assert cf._gram_inv.shape == (2, 2)

    def test_gram_inv_matches_direct_computation(self, reference_data):
        """_gram_inv must equal the 2x2 inverse computed directly from the
        linear segment observations, within 1e-10.
        """
        pep = "VTAVVESPEGER"
        mask = reference_data.peptide == pep
        x = reference_data.concentration[mask]
        y = reference_data.area[mask]
        w = inverse_sqrt_weights(x)
        W = w**2

        cf = PiecewiseCF(n_boot_reps=0, seed=42).fit(x, y)
        knot_x = cf.params_["knot_x"]

        # Recompute G directly from the linear segment
        lin_mask = x > knot_x
        xL = x[lin_mask]
        WL = W[lin_mask]
        G = np.array(
            [
                [np.sum(WL * xL**2), np.sum(WL * xL)],
                [np.sum(WL * xL), np.sum(WL)],
            ]
        )
        expected_inv = np.linalg.inv(G)

        np.testing.assert_allclose(
            cf._gram_inv,
            expected_inv,
            rtol=1e-10,
            err_msg=f"_gram_inv does not match direct computation for {pep}",
        )


# ---------------------------------------------------------------------------
# Test 5: summary() returns finite values for fitted peptides
# ---------------------------------------------------------------------------


class TestSummary:
    def test_summary_finite_for_finite_lod_peptides(self, all_cf_fits):
        """summary() must contain finite values for slope, intercept_linear,
        intercept_noise, knot_x, and n_points for all peptides.
        LOD and LOQ may be inf for degenerate peptides.
        """
        required_finite_keys = [
            "slope",
            "intercept_linear",
            "intercept_noise",
            "knot_x",
            "n_points",
        ]
        failures = []
        for pep, cf in all_cf_fits.items():
            s = cf.summary()
            for k in required_finite_keys:
                if not np.isfinite(s[k]):
                    failures.append((pep, k, s[k]))
        assert not failures, f"Non-finite summary keys: {failures}"

    def test_summary_keys_complete(self, all_cf_fits):
        cf = next(iter(all_cf_fits.values()))
        keys = set(cf.summary().keys())
        assert {
            "slope",
            "intercept_linear",
            "intercept_noise",
            "knot_x",
            "lod",
            "loq",
            "n_points",
        } <= keys

    def test_predict_shape(self, reference_data):
        """predict() must return an array of the same length as the input."""
        pep = "KQAIVQK"
        mask = reference_data.peptide == pep
        x = reference_data.concentration[mask]
        y = reference_data.area[mask]
        cf = PiecewiseCF(n_boot_reps=0, seed=42).fit(x, y)
        x_new = np.linspace(0.001, 1.0, 20)
        preds = cf.predict(x_new)
        assert preds.shape == (20,)
        assert np.all(preds >= cf.params_["intercept_noise"] - 1e-10)


# ---------------------------------------------------------------------------
# Test 6: model registry
# ---------------------------------------------------------------------------


class TestRegistry:
    def test_piecewise_cf_in_registry(self):
        assert "piecewise_cf" in MODEL_REGISTRY
        assert MODEL_REGISTRY["piecewise_cf"] is PiecewiseCF


# ---------------------------------------------------------------------------
# Test 7: edge-case correctness (bugs found during rigorous C3 review)
# ---------------------------------------------------------------------------


class TestEdgeCases:
    """Targeted tests for properties and failure modes found during code review.

    These tests were written BEFORE the fixes were confirmed to pass — i.e.,
    they are genuine regression guards, not post-hoc tests designed to pass.
    """

    # ------------------------------------------------------------------
    # Bug: _gram_inv stored for slope=0 (constraint 1 fired)
    # ------------------------------------------------------------------

    def test_gram_inv_is_none_when_slope_clamped_to_zero(self):
        """When _fit_and_constrain clamps slope to 0 (negative unconstrained
        slope in the linear region), the actual fit is a 1-parameter weighted
        mean.  Storing a 2x2 Gram inverse for a 2-parameter model that was
        never fit would produce wrong covariance estimates in C4.  It must be
        None instead.
        """
        # Noise region: flat at y ~ 10
        # "Linear" region: decreasing y (forces negative unconstrained slope,
        #  which constraint 1 clamps to 0)
        rng = np.random.default_rng(7)
        x_noise = np.repeat([0.1, 0.5, 1.0], 3)
        y_noise = 10 + rng.normal(0, 0.2, 9)
        x_lin = np.repeat([2.0, 5.0, 10.0], 3)
        y_lin = 12 - 0.5 * x_lin + rng.normal(0, 0.2, 9)  # decreasing
        x = np.concatenate([x_noise, x_lin])
        y = np.concatenate([y_noise, y_lin])

        cf = PiecewiseCF(n_boot_reps=0, seed=42).fit(x, y)
        assert cf.params_["slope"] == 0.0, (
            "Test setup failure: expected constraint 1 to clamp slope to 0"
        )
        assert cf._gram_inv is None, (
            "_gram_inv must be None when slope was clamped to 0 by constraint 1; "
            "the 2x2 Gram inverse belongs to an unconstrained model that was never fit"
        )

    # ------------------------------------------------------------------
    # Sort-order invariance
    # ------------------------------------------------------------------

    def test_lod_invariant_to_sort_order(self, reference_data):
        """PiecewiseCF.lod() must return the same value regardless of the
        order in which (x, y) pairs are presented.  find_knot uses unique(x)
        for candidate knots and boolean masks throughout — all sort-order
        independent — but this must be confirmed end-to-end.
        """
        pep = "SVEDFMAAMQR"
        mask = reference_data.peptide == pep
        x = reference_data.concentration[mask]
        y = reference_data.area[mask]

        rng = np.random.default_rng(99)
        perm = rng.permutation(len(x))

        lod_original = PiecewiseCF(n_boot_reps=0, seed=42).fit(x, y).lod()
        lod_shuffled = PiecewiseCF(n_boot_reps=0, seed=42).fit(x[perm], y[perm]).lod()

        # Floating-point aggregates (sum of W, W*x, W*x^2) accumulate in a
        # different order → up to ~1 ULP difference.  rtol=1e-10 distinguishes
        # "same result, FP noise" from "different knot selected" (which would
        # differ by multiple percent).
        np.testing.assert_allclose(
            lod_original,
            lod_shuffled,
            rtol=1e-10,
            err_msg=(
                f"LOD changed with sort order beyond FP noise: "
                f"sorted={lod_original:.10f}, shuffled={lod_shuffled:.10f}"
            ),
        )

    # ------------------------------------------------------------------
    # predict() monotonicity
    # ------------------------------------------------------------------

    def test_predict_nondecreasing_on_positive_x(self, reference_data):
        """predict() implements max(c, a*x + b) with a >= 0 and c >= b.  For
        any sorted non-negative x grid, predictions must be non-decreasing.
        """
        for pep in ["SVEDFMAAMQR", "ADTGIAVEGATDAAR", "KQAIVQK"]:
            mask = reference_data.peptide == pep
            x = reference_data.concentration[mask]
            y = reference_data.area[mask]
            cf = PiecewiseCF(n_boot_reps=0, seed=42).fit(x, y)

            x_new = np.linspace(0.0, float(np.max(x)) * 2, 500)
            preds = cf.predict(x_new)
            diffs = np.diff(preds)
            assert np.all(diffs >= -1e-12), (
                f"{pep}: predict() is not non-decreasing; min diff = {diffs.min():.2e}"
            )

    # ------------------------------------------------------------------
    # Refit clears all cached state
    # ------------------------------------------------------------------

    def test_refit_clears_caches_and_bootstrap(self, reference_data):
        """Calling fit() a second time on the same model object must discard
        all cached LOD, LOQ, and bootstrap state from the first fit.  Stale
        caches after refit would silently return results for the wrong data.
        """
        pep = "ADTGIAVEGATDAAR"
        mask = reference_data.peptide == pep
        x = reference_data.concentration[mask]
        y = reference_data.area[mask]

        cf = PiecewiseCF(n_boot_reps=20, seed=42).fit(x, y)
        # Populate all caches
        _ = cf.lod()
        _ = cf.loq()
        assert cf._lod_cache, "pre-condition: _lod_cache must be populated"
        assert cf._loq_cache, "pre-condition: _loq_cache must be populated"
        assert cf._boot_summary is not None, "pre-condition: bootstrap must be run"

        # Refit — caches must be wiped
        cf.fit(x, y)
        assert not cf._lod_cache, "_lod_cache must be empty after refit"
        assert not cf._loq_cache, "_loq_cache must be empty after refit"
        assert cf._boot_summary is None, "_boot_summary must be None after refit"
        assert cf._x_grid is None, "_x_grid must be None after refit"

    # ------------------------------------------------------------------
    # LOQ with zero bootstrap replicates
    # ------------------------------------------------------------------

    def test_loq_zero_boot_reps_returns_inf(self, reference_data):
        """PiecewiseCF(n_boot_reps=0).loq() must return np.inf without raising.

        With 0 bootstrap replicates the CV profile is undefined; LOQ is
        undeterminable.  inf is the correct sentinel — not 0, not NaN, not
        the LOD value.
        """
        pep = "ADTGIAVEGATDAAR"  # finite LOD: bootstrap actually runs (0 reps)
        mask = reference_data.peptide == pep
        x = reference_data.concentration[mask]
        y = reference_data.area[mask]

        cf = PiecewiseCF(n_boot_reps=0, seed=42).fit(x, y)
        assert np.isfinite(cf.lod()), "pre-condition: LOD must be finite for this test"
        loq = cf.loq()
        assert loq == np.inf, f"loq() with n_boot_reps=0 must return inf, got {loq}"


# ---------------------------------------------------------------------------
# Test 8: covariance() — C4
# ---------------------------------------------------------------------------


class TestCovariance:
    """Tests for PiecewiseCF.covariance().

    The method returns the 2x2 parameter covariance matrix for the linear
    segment: Cov = MSE_linear * _gram_inv where MSE uses ddof=2 (slope +
    intercept).  Returns None for unfitted models or slope=0 models.
    """

    def test_covariance_shape_and_type(self, reference_data):
        """covariance() must return a (2, 2) numpy array for a normally fitted
        peptide (finite LOD, slope > 0).
        """
        pep = "ADTGIAVEGATDAAR"
        mask = reference_data.peptide == pep
        x = reference_data.concentration[mask]
        y = reference_data.area[mask]
        cf = PiecewiseCF(n_boot_reps=0, seed=42).fit(x, y)
        assert cf.params_["slope"] > 0, "pre-condition: peptide must have slope > 0"

        cov = cf.covariance()
        assert cov is not None, "covariance() must not return None for a slope>0 peptide"
        assert isinstance(cov, np.ndarray)
        assert cov.shape == (2, 2)

    def test_covariance_diagonal_nonnegative(self, reference_data):
        """Diagonal entries of the covariance matrix are variances — they must
        be non-negative for any valid WLS fit.
        """
        pep = "ADTGIAVEGATDAAR"
        mask = reference_data.peptide == pep
        x = reference_data.concentration[mask]
        y = reference_data.area[mask]
        cf = PiecewiseCF(n_boot_reps=0, seed=42).fit(x, y)
        cov = cf.covariance()
        assert cov is not None
        assert cov[0, 0] >= 0, f"var(slope) = {cov[0, 0]} is negative"
        assert cov[1, 1] >= 0, f"var(intercept) = {cov[1, 1]} is negative"

    def test_covariance_is_symmetric(self, reference_data):
        """The covariance matrix must be symmetric to machine precision."""
        pep = "ADTGIAVEGATDAAR"
        mask = reference_data.peptide == pep
        x = reference_data.concentration[mask]
        y = reference_data.area[mask]
        cf = PiecewiseCF(n_boot_reps=0, seed=42).fit(x, y)
        cov = cf.covariance()
        assert cov is not None
        np.testing.assert_allclose(
            cov,
            cov.T,
            atol=1e-15,
            err_msg="covariance matrix is not symmetric",
        )

    def test_covariance_matches_lstsq_reference(self, reference_data):
        """The covariance matrix must agree with a reference computed directly
        via np.linalg.lstsq on the same linear segment, within rtol=1e-8.

        Reference formula:
            H = W^(1/2) * [x_lin | 1]    (design matrix, weighted by sqrt(W))
            beta, _, _, _ = lstsq(H, W^(1/2) * y_lin)
            residuals = y_lin - (a * x_lin + intercept)
            wrss = sum(W * residuals^2)
            mse = wrss / (n_lin - 2)
            cov_ref = mse * inv(H.T @ H)    # == mse * _gram_inv
        """
        pep = "VTAVVESPEGER"
        mask = reference_data.peptide == pep
        x = reference_data.concentration[mask]
        y = reference_data.area[mask]
        w = inverse_sqrt_weights(x)
        W = w**2

        cf = PiecewiseCF(n_boot_reps=0, seed=42).fit(x, y)
        assert cf.params_["slope"] > 0, "pre-condition: test peptide must have slope > 0"

        knot_x = cf.params_["knot_x"]
        lin_mask = x > knot_x
        x_lin = x[lin_mask]
        y_lin = y[lin_mask]
        W_lin = W[lin_mask]
        n_lin = int(np.sum(lin_mask))

        # Build weighted design matrix
        sqrt_W = np.sqrt(W_lin)
        H = np.column_stack([x_lin * sqrt_W, sqrt_W])  # [x | 1] * sqrt(W)
        beta, _, _, _ = np.linalg.lstsq(H, y_lin * sqrt_W, rcond=None)
        a_ref, b_ref = beta[0], beta[1]

        residuals = y_lin - (a_ref * x_lin + b_ref)
        wrss = float(np.sum(W_lin * residuals**2))
        mse = wrss / (n_lin - 2)

        G = H.T @ H  # = [[sum(W*x^2), sum(W*x)], [sum(W*x), sum(W)]]
        cov_ref = mse * np.linalg.inv(G)

        cov_cf = cf.covariance()
        assert cov_cf is not None
        np.testing.assert_allclose(
            cov_cf,
            cov_ref,
            rtol=1e-8,
            err_msg="covariance() does not match lstsq reference",
        )

    def test_covariance_none_when_not_fitted(self):
        """covariance() must return None (not raise) before fit() is called."""
        cf = PiecewiseCF(n_boot_reps=0, seed=42)
        assert cf.covariance() is None

    def test_covariance_none_when_slope_zero(self):
        """covariance() must return None when slope was clamped to 0.
        The linear segment was fit as a weighted mean (1-parameter); the
        2x2 Gram inverse is undefined for that model.
        """
        rng = np.random.default_rng(7)
        x_noise = np.repeat([0.1, 0.5, 1.0], 3)
        y_noise = 10 + rng.normal(0, 0.2, 9)
        x_lin = np.repeat([2.0, 5.0, 10.0], 3)
        y_lin = 12 - 0.5 * x_lin + rng.normal(0, 0.2, 9)  # decreasing → slope=0

        cf = PiecewiseCF(n_boot_reps=0, seed=42).fit(
            np.concatenate([x_noise, x_lin]),
            np.concatenate([y_noise, y_lin]),
        )
        assert cf.params_["slope"] == 0.0, "pre-condition: slope must be clamped to 0"
        assert cf.covariance() is None, (
            "covariance() must return None when slope=0; "
            "the 2x2 Gram inverse does not correspond to the fitted model"
        )


# ---------------------------------------------------------------------------
# Test 9: vectorized bootstrap (H6) — C5
# ---------------------------------------------------------------------------


class TestVectorizedBootstrap:
    """Vectorized bootstrap: correctness, determinism, and exact loop agreement.

    The vectorized path gates each candidate k on whether k is an INTERIOR
    point of unique(xb_i) for replicate i — matching find_knot(xb)[1:-1].
    This ensures knot selection is bit-identical to the loop path.  The only
    residual differences are sub-ULP FP accumulation in numpy's 2-D axis=1
    reductions vs the loop's 1-D scalar sums (max ~2e-7 absolute on the
    reference dataset, <1e-14 relative — machine-precision noise).

    Tests here verify:
    - Determinism (same seed → same output)
    - Different seeds → different output
    - Memory guard fallback emits ResourceWarning and returns valid summary
    - LOD regression is unaffected (LOD is analytical, no bootstrap)
    - All 26 finite-LOD reference peptides agree with the loop path to 1e-6
      in CV and 1e-3 relative in mean predictions (covers FP noise budget)
    - ADTGIAVEGATDAAR in particular agrees to 1e-10 (no FP noise for seed=42)
    """

    @pytest.fixture()
    def pep_data(self, reference_data):
        pep = "ADTGIAVEGATDAAR"
        mask = reference_data.peptide == pep
        x = reference_data.concentration[mask]
        y = reference_data.area[mask]
        w = inverse_sqrt_weights(x)
        W = w**2
        return x, y, W

    @pytest.fixture()
    def x_grid(self, pep_data):
        x, _, _ = pep_data
        return np.linspace(x.min(), x.max(), 200)

    # H6 — ADTGIAVEGATDAAR: shows 0 FP noise, so can hold to 1e-10
    def test_h6_cv_profile_agrees_with_loop(self, pep_data, x_grid):
        """ADTGIAVEGATDAAR seed=42 shows zero FP accumulation; CV must agree
        to better than 1e-10."""
        x, y, W = pep_data
        n_reps, seed = 100, 42

        _, summ_loop = _bootstrap_loop_cf(x, y, W, x_grid, n_reps, seed)
        _, summ_vec = _bootstrap_vectorized_cf(x, y, W, x_grid, n_reps, seed)

        cv_loop = summ_loop["cv"]
        cv_vec = summ_vec["cv"]

        finite = np.isfinite(cv_loop) & np.isfinite(cv_vec)
        assert finite.any(), "no finite CV values to compare"
        max_diff = float(np.max(np.abs(cv_loop[finite] - cv_vec[finite])))
        assert max_diff < 1e-10, (
            f"H6 FAIL for ADTGIAVEGATDAAR: max |cv_loop - cv_vec| = {max_diff:.3e}"
        )

    def test_h6_mean_pred_agrees_with_loop(self, pep_data, x_grid):
        """Mean predictions also agree to < 1e-10 for ADTGIAVEGATDAAR seed=42."""
        x, y, W = pep_data
        n_reps, seed = 100, 42

        _, summ_loop = _bootstrap_loop_cf(x, y, W, x_grid, n_reps, seed)
        _, summ_vec = _bootstrap_vectorized_cf(x, y, W, x_grid, n_reps, seed)

        max_diff = float(np.max(np.abs(summ_loop["mean"] - summ_vec["mean"])))
        assert max_diff < 1e-10, (
            f"H6 FAIL for ADTGIAVEGATDAAR: max |mean_loop - mean_vec| = {max_diff:.3e}"
        )

    def test_vectorized_is_deterministic(self, pep_data, x_grid):
        """Two calls with the same seed must produce bit-identical predictions."""
        x, y, W = pep_data
        pred1, _ = _bootstrap_vectorized_cf(x, y, W, x_grid, n_reps=50, seed=7)
        pred2, _ = _bootstrap_vectorized_cf(x, y, W, x_grid, n_reps=50, seed=7)
        np.testing.assert_array_equal(
            pred1, pred2, err_msg="vectorized bootstrap is not deterministic"
        )

    def test_vectorized_different_seeds_differ(self, pep_data, x_grid):
        """Different seeds must produce different replicate matrices."""
        x, y, W = pep_data
        pred1, _ = _bootstrap_vectorized_cf(x, y, W, x_grid, n_reps=50, seed=1)
        pred2, _ = _bootstrap_vectorized_cf(x, y, W, x_grid, n_reps=50, seed=2)
        assert not np.array_equal(pred1, pred2), "different seeds produced identical predictions"

    def test_memory_guard_fallback(self, pep_data, x_grid, monkeypatch):
        """When memory limit is tiny, a ResourceWarning must be emitted and
        the call must still return a valid (non-all-inf) summary via the loop
        fallback.
        """
        import loqculate.models.piecewise_cf as _mod

        monkeypatch.setattr(_mod, "VECTORIZED_BOOTSTRAP_MEMORY_LIMIT_MB", 0)

        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            x, y, W = pep_data
            _, summ = _bootstrap_vectorized_cf(x, y, W, x_grid, n_reps=20, seed=42)

        resource_warnings = [w for w in caught if issubclass(w.category, ResourceWarning)]
        assert resource_warnings, "expected a ResourceWarning from the memory guard"

        cv = summ["cv"]
        assert np.any(np.isfinite(cv)), "fallback summary must contain finite CV values"

    def test_lod_regression_unchanged(self, all_cf_fits):
        """Switching the default bootstrap path must not alter LOD values.

        LOD is computed analytically (no bootstrap involved), so all pinned
        values should be reproduced to within the original tolerance.
        """
        lod_values = {pep: fit.lod() for pep, fit in all_cf_fits.items()}
        for pep, expected in _PINNED_LOD.items():
            got = lod_values[pep]
            if expected is None:
                assert got is None, f"{pep}: expected LOD=None, got {got}"
            else:
                assert got is not None, f"{pep}: expected LOD={expected}, got None"
                if np.isinf(expected):
                    assert np.isinf(got), f"{pep}: expected inf LOD, got {got}"
                else:
                    assert abs(got - expected) < 1e-4, (
                        f"{pep}: LOD regression after C5: expected {expected}, got {got}"
                    )

    def test_h6_all_peptides_agree_with_loop(self, reference_data):
        """Vectorized path must agree with the loop path on ALL 26 finite-LOD
        reference peptides (n_reps=200, seed=42).

        Tolerance: max|cv_diff| < 1e-6 and max|mean_diff|/mean_pred < 1e-6.
        This comfortably covers the observed FP accumulation budget (~2e-7 abs,
        <1e-14 relative) while being tight enough to catch any knot-selection
        disagreement (which produces diffs of order 1e2–1e4 absolute).
        """
        n_reps, seed = 200, 42
        failures = []
        for pep in np.unique(reference_data.peptide):
            mask = reference_data.peptide == pep
            x = reference_data.concentration[mask]
            y = reference_data.area[mask]
            w = inverse_sqrt_weights(x)
            W = w**2

            cf = PiecewiseCF(n_boot_reps=0, seed=seed).fit(x, y)
            lod = cf.lod()
            if not np.isfinite(lod):
                continue

            x_grid = np.linspace(lod, float(np.max(x)), num=100)
            _, sl = _bootstrap_loop_cf(x, y, W, x_grid, n_reps, seed)
            _, sv = _bootstrap_vectorized_cf(x, y, W, x_grid, n_reps, seed)

            fin = np.isfinite(sl["cv"]) & np.isfinite(sv["cv"])
            d_cv = float(np.max(np.abs(sl["cv"][fin] - sv["cv"][fin]))) if fin.any() else 0.0

            mean_scale = float(np.nanmean(np.abs(sl["mean"])))
            d_mean_rel = float(np.max(np.abs(sl["mean"] - sv["mean"]))) / max(mean_scale, 1e-12)

            if d_cv >= 1e-6 or d_mean_rel >= 1e-6:
                failures.append((pep, d_cv, d_mean_rel))

        assert not failures, (
            f"Vectorized/loop disagreement on {len(failures)} peptide(s):\n"
            + "\n".join(
                f"  {p}: max|cv_diff|={dc:.3e}, max|mean_diff|/mean={dm:.3e}"
                for p, dc, dm in failures
            )
        )
